#include <iostream>
#include <string>

using namespace std;

void ln(string line) {
cout << line << "\n";
}

string prefix = "com.yourcompany.apps";
string appname = "Untitled";

int main(int argc, char *argv[])
{
    if (argc==3) {
        prefix = string(argv[1]);
        appname = string(argv[2]);
    } else if (argc==2) {
        string pkgname = string(argv[1]);
       std::size_t found = pkgname.find_last_of(".");
       prefix = pkgname.substr(0,found);
       appname = pkgname.substr(found+1);
    }
   ln("//786// Generated by cfgglue");
   ln("package " + prefix + "." + appname + ";");
   ln("public class "+appname+" extends " + prefix + ".BaseActivity{} ");
   return 0;
}